
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 45
#define YY_END_OF_BUFFER 46
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[561] =
    {   0,
        0,    0,   46,   43,   23,   45,   29,   27,   36,   43,
       26,   26,   37,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   34,   35,   43,   43,   43,   43,   32,
       33,   42,    0,   24,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   26,   26,    0,   41,
        0,   26,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   25,    0,    9,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   26,   26,    0,    0,
       26,   26,   39,   39,   39,   39,   38,   39,   39,   39,
       39,   39,   38,   39,   39,   38,   39,   38,   38,   38,
       38,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   11,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   40,   26,
        0,    0,    0,    0,    0,    0,   39,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   31,    0,

       28,    0,    0,   25,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   18,
        0,    0,   26,   26,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   30,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   13,    0,
        0,   10,    0,    0,   12,    0,    0,   38,    0,    0,

        0,    0,    0,    0,    0,    0,   44,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   20,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    7,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       19,    0,    0,    0,    0,    0,    0,    0,    0,   25,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        6,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    4,    0,    0,    5,   15,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    2,    0,    0,   21,    0,   25,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   16,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       17,    0,    0,    0,   14,    0,    0,    0,    0,    0,
       25,    0,    0,    0,    0,    0,    0,    0,    0,    3,
        0,    0,    0,    0,    0,    0,   25,    0,    0,    8,
        0,    0,    0,    0,    0,   22,    0,    0,   25,    0,
        0,    0,    0,    0,    0,    0,    0,    1,    1,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    6,    6,    6,    6,    6,    6,
        6,    6,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   17,   18,   18,   18,   18,   19,    6,    6,
        6,    6,    6,   20,   21,    6,    6,   22,   23,   24,
        6,    6,    6,   25,    6,    6,   26,   27,   28,    6,
        6,   29,   30,   31,    6,    6,   32,    6,    6,    6,
       33,   34,   35,    6,   36,    6,   37,   38,   39,   40,

       41,   42,   43,   44,   45,    6,    6,   46,   47,   48,
       49,   50,    6,   51,   52,   53,   54,   55,   56,   57,
       58,    6,   59,    6,   60,    6,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[61] =
    {   0,
        1,    1,    1,    1,    2,    2,    3,    2,    2,    2,
        4,    3,    5,    5,    5,    5,    5,    5,    2,    2,
        2,    2,    4,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    3,    2,    2,    6,    7,    6,    6,
        5,    7,    2,    2,    2,    2,    2,    3,    2,    2,
        3,    2,    3,    3,    2,    2,    2,    2,    2,    2
    } ;

static yyconst flex_int16_t yy_base[578] =
    {   0,
        0,    0, 1123, 1124, 1124, 1124, 1119,   56, 1124,  104,
      112,  113, 1124,   75, 1080,   86,   89,   91, 1071, 1080,
       93,   87, 1077, 1124, 1124, 1080, 1062, 1074, 1063, 1124,
     1124, 1124,  148, 1124,  168,  184,  219, 1062, 1063, 1080,
       95,   94, 1069, 1055, 1057,  101,  102, 1053, 1069,  104,
     1056, 1067, 1062, 1063,  119,  105,  128,  186,  197,  203,
      230,  218, 1050, 1057, 1060, 1060, 1052, 1048,  125,  147,
     1047, 1039, 1040, 1039, 1041, 1042, 1035, 1047, 1047, 1040,
     1039, 1031, 1029, 1124,  254, 1124,  236,  265,  289, 1037,
     1033, 1075, 1026, 1030, 1023, 1035, 1035,    0, 1033, 1021,

     1020, 1018, 1017, 1023, 1016,  221, 1027, 1027, 1018, 1011,
     1012, 1005, 1007, 1019, 1013, 1017,  251,  300,  271,  311,
      318,  253, 1012, 1002, 1014, 1003, 1013,  998,  993, 1009,
     1010, 1124, 1008, 1006,  997,  991,  991, 1003,  991,  989,
      992,  987,  992,  983,  995,  335,  347,  364,  376,  199,
      251, 1015,  303,  304,  292,  314,  362,    0,  997,  994,
      982,  986,  989,  983,  984, 1124,  975,  981,  988,  983,
      967,  981,  968,  972,  978, 1011,  966,  387, 1124,  345,
      970,  963,  967,  959,  975,  974, 1124,  966,  972,  961,
      969,  955,  964,  967,  951,  962,  960,  959, 1124,  948,

     1124,  398,  396,  406,  961,  960,  169,  945,  958,  942,
      953,  951,    0,  938,  939,  943,  935,  939,  950,  932,
      931,  944,  929,  974,  939,  938,  971,  938,  923, 1124,
      968,  424,  430,  438,  921,  935,  935,  913,  919,  911,
      930,  926,  926,  918,  906,  923,  925,  909, 1124,  912,
      437,  449,  305,  918,  917,  283,  920,  907,  916,  913,
      321,  912,  911,  285,  914,  901,  910,  907,  889,  888,
      256,  891,  904,  885,  902,  904,  888,    0,  898,  893,
      900,  891,  895,  881,  896,  881,  890,  885, 1124,  888,
      880, 1124,  890,  919, 1124,  884,  873, 1124,  865,  881,

      870,  883,  881,  881,  859,  876, 1124,  864,  871,  874,
      874,  863,  176,  287,  855,  856,  858,  856,  863,  866,
      866,  855,  326,  289,  847,  848,  850,  380, 1124,    0,
      862,  861,  839,  856,  855,  844,  835,  851,  850,  849,
      846,  881,  835,  837,  832,  848,  830, 1124,  831,  823,
      829,  821,  837,  819,  839,  452,  453,  463,  464,  467,
      468,  471,  475,  391,  476,  479,  480,  484,  483,  489,
      488,  493,  494,  501,  504,  402,  513,  517,  498,    0,
      817,  816,  836,  836,  818,  834,  817,  828,  810,  814,
     1124,  858,  816,  822,  814,  820,  809,  801,  542,  554,

      812,  805,  809,  801,  817,  518,  809,  805,  813,  809,
      560,  803,  796,  800,  792,  808,  527,  800,  796,  804,
      800,    0,  782,  802,  793,  784,  829,  799,  781,  826,
     1124,  825,  791,  793,  789,  566,  572,  775,  789,  789,
      774,  786,  782,  775,  768,  782,  782,  767,  779,  775,
      768,    0,  761,  764,  771, 1124,  758,  803, 1124, 1124,
      773,  761,  800,  531,  539,  765,  754,  746,  762,  751,
      763,  759,  748,  740,  756,  745,  757,  787,  745,  719,
      719, 1124,  722,  707, 1124,  535,  548,  578,  696,  688,
      613,  524,  513,  487,  489,  494, 1124,  520,  463,  472,

      457,  495,  581,  587,  593,  597,  603,  609,  441,  426,
     1124,  399,  388,  388, 1124,  126,  512,  368,  346,  331,
      613,  618,  623,  336,  294,  244,  628,  634,  245, 1124,
      214,  534,  646,  212,  224,  641,  646,  653,  182, 1124,
      658,  664,  201,  678,  679, 1124,  674,  680,  686,  692,
      698,  704,  710,  716,  722,  161,  160, 1124, 1124, 1124,
      737,  739,  742,  746,  748,  749,  753,  754,  758,  762,
      765,  770,  773,  776,  779,  782,  785
    } ;

static yyconst flex_int16_t yy_def[578] =
    {   0,
      560,    1,  560,  560,  560,  560,  560,  560,  560,  560,
      561,  562,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,    8,  560,   33,   33,   33,   33,   33,   33,
       33,   33,   33,  563,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,  560,  564,  560,  560,
      560,  565,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,   33,  560,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,  566,   33,   33,

       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,  564,  560,  560,  560,
      560,  567,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,  568,   33,   33,
       33,   33,   33,   33,   33,  560,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,  560,  560,  569,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,

      560,   33,   33,  560,   33,   33,  570,   33,   33,   33,
       33,   33,  571,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,  560,
       33,  560,  560,  569,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
      560,  560,  560,  560,  560,  560,  560,  560,   33,   33,
      570,  572,   33,   33,   33,   33,   33,  573,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,  560,   33,
       33,  560,   33,   33,  560,  560,  560,  560,  560,  560,

      560,  560,  560,  560,  560,  560,  560,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,   33,  560,  574,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,  560,  560,  560,
      560,  560,  560,  560,  560,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  575,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
      560,   33,   33,   33,   33,   33,  560,  560,   33,  560,

       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  576,   33,   33,   33,   33,   33,   33,   33,   33,
      560,   33,   33,   33,   33,   33,  560,   33,   33,   33,
       33,   33,   33,   33,  560,  560,  560,  560,  560,  560,
      560,  577,   33,   33,   33,  560,   33,   33,  560,  560,
       33,   33,   33,   33,  560,   33,   33,   33,   33,   33,
       33,  560,  560,  560,  560,  560,  560,   33,   33,   33,
       33,  560,   33,   33,  560,   33,  560,  560,   33,   33,
       33,   33,  560,  560,  560,  560,  560,   33,   33,   33,

       33,   33,   33,   33,   33,  560,  560,  560,   33,  560,
      560,   33,   33,   33,  560,   33,  560,   33,   33,   33,
      560,   33,  560,   33,   33,   33,  560,   33,   33,  560,
       33,  560,   33,   33,   33,  560,  560,   33,   33,  560,
      560,   33,   33,  560,   33,  560,  560,   33,  560,  560,
       33,  560,   33,  560,   33,  560,   33,  560,  560,    0,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560
    } ;

static yyconst flex_int16_t yy_nxt[1185] =
    {   0,
        4,    5,    6,    7,    5,    4,    8,    4,    9,   10,
        4,    4,   11,   12,   12,   12,   12,   12,   13,    4,
       14,   15,    4,   16,   17,   18,   19,   20,    4,   21,
       22,   23,   24,    4,   25,    4,    4,    4,    4,    4,
        4,   26,    4,    4,    4,    4,    4,   27,    4,    4,
       28,    4,   29,    4,    4,    4,    4,    4,   30,   31,
       33,   33,   34,   33,   33,   35,   33,   33,   36,   37,
       37,   37,   37,   37,   33,   33,   33,   33,   33,   38,
       33,   39,   33,   33,   40,   41,   42,   43,   33,   44,
       33,   33,   33,   33,   45,   46,   47,   48,   33,   49,

       50,   51,   33,   52,   33,   33,   53,   54,   55,   56,
       33,   33,   33,   33,   33,   33,   57,   58,   58,   58,
       58,   58,   59,   59,   63,   68,   66,   70,   64,   74,
       77,   93,  521,   75,   61,   61,   67,   95,   59,   71,
       78,  100,   69,  106,  522,  101,   76,   96,   94,  102,
       61,  107,   61,   61,   84,  115,  116,   33,  103,  112,
       33,   33,   33,   33,   33,   33,  559,  558,   61,  113,
      129,   33,  130,   33,  114,   84,   33,   33,   33,   33,
       36,   85,   85,   85,   85,   85,   33,   33,   33,   33,
       86,   33,   33,   33,   87,   33,   59,  131,   33,   33,

       33,   33,  272,  203,  132,  204,   88,  546,   61,  118,
      118,  118,  118,  118,  118,  119,  119,  119,  119,  119,
      119,  361,  543,  362,   88,   86,   61,  166,   59,   87,
      540,   89,   89,   89,   89,   89,   89,  120,  205,  120,
       61,   88,  121,  121,  121,  121,  121,  121,  147,  147,
      147,  147,  147,  147,  539,  203,  167,  204,   61,   88,
       86,   59,  329,   59,   87,  535,  146,  146,  146,  146,
      146,  146,  148,   61,  148,   61,   88,  149,  149,  149,
      149,  149,  149,  179,  179,  179,  179,  179,  179,  272,
      206,   61,  534,   61,   88,   86,  203,  531,  204,   87,

      530,   89,   89,   89,   89,   89,   89,  203,  203,  204,
      204,   88,  118,  118,  118,  118,  118,  118,  203,  312,
      204,  322,  178,  121,  121,  121,  121,  121,  121,   88,
      121,  121,  121,  121,  121,  121,  313,  363,  323,  375,
      178,   86,  210,  209,  364,   87,  376,  146,  146,  146,
      146,  146,  146,   86,  308,   59,  208,   88,  309,  147,
      147,  147,  147,  147,  147,  211,  203,   61,  204,  202,
      318,  373,  529,  374,  319,   88,  149,  149,  149,  149,
      149,  149,   86,  526,  203,   61,  204,  202,  149,  149,
      149,  149,  149,  149,  232,  399,  232,  400,  525,  233,

      233,  233,  233,  233,  233,  251,  411,  251,  411,  212,
      252,  252,  252,  252,  252,  252,  253,  254,  524,  255,
      256,  257,  258,  259,  520,  260,  261,  262,  519,  263,
      264,  265,  266,  267,  518,  268,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,   59,  252,
      252,  252,  252,  252,  252,   86,  399,  399,  400,  400,
       61,  252,  252,  252,  252,  252,  252,  399,  399,  400,
      400,  399,  399,  400,  400,  399,  417,  400,   61,  399,
      399,  400,  400,  399,  399,  400,  400,  411,  411,  411,
      411,  406,  411,  411,  411,  411,  401,  411,  411,  411,

      411,  515,  411,  403,  411,  411,  402,  411,  411,  514,
      411,  406,  513,  407,  404,  512,  408,  411,  523,  411,
      405,  411,  399,  411,  400,  406,  511,  409,  412,  414,
      523,  411,  410,  411,  510,  486,  413,  487,  415,  417,
      536,  417,  418,  488,  417,  488,  416,  503,  504,  505,
      421,  417,  536,  419,  436,  436,  436,  436,  436,  436,
      506,  507,  508,  417,  509,  420,  437,  437,  437,  437,
      437,  437,  437,  437,  437,  437,  437,  437,  464,  464,
      464,  464,  464,  464,  465,  465,  465,  465,  465,  465,
      506,  507,  508,  516,  516,  516,  516,  516,  516,  516,

      516,  516,  516,  516,  516,  516,  516,  516,  516,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  527,  527,  527,  527,  527,
      528,  528,  528,  528,  528,  527,  527,  527,  527,  527,
      532,  532,  532,  532,  532,  532,  533,  533,  533,  533,
      533,  533,  537,  541,  541,  541,  541,  541,  541,  541,
      541,  541,  541,  406,  538,  542,  542,  542,  542,  542,
      544,  544,  544,  544,  544,  544,  545,  545,  545,  545,
      545,  545,  547,  548,  547,  549,  550,  550,  550,  550,
      550,  550,  551,  551,  551,  551,  551,  551,  550,  550,

      550,  550,  550,  550,  552,  552,  552,  552,  552,  552,
      553,  553,  553,  553,  553,  553,  554,  554,  554,  554,
      554,  554,  555,  555,  555,  555,  555,  555,  556,  556,
      556,  556,  556,  556,  557,  557,  557,  557,  557,  557,
       60,   60,   62,   62,   33,  406,  406,  502,   33,  117,
      117,  122,  122,  158,  158,  158,  180,  180,  213,  213,
      213,  234,  234,  271,  271,  271,  271,  271,  271,  278,
      278,  278,  271,  501,  500,  499,  271,   33,   33,   33,
      380,  380,  380,  422,  422,  422,  452,  452,  452,  271,
      271,  271,  498,  497,  496,  417,  495,  417,  494,  493,

      492,  406,  491,  406,  490,  489,  485,  484,  483,  482,
      481,  480,  479,  478,  477,  476,  475,  474,  473,  472,
      417,  471,  470,  469,  468,  467,  466,  406,  463,  462,
      461,  460,  459,  458,  457,  456,  455,  454,  453,  328,
      451,  450,  449,  417,  448,  447,  446,  445,  417,  444,
      443,  442,  406,  441,  440,  439,  438,  406,  298,  187,
      435,  434,  433,  432,  431,  430,  429,  428,  427,  426,
      425,  424,  423,  328,  328,  398,  298,  397,  298,  187,
      187,  187,  396,  395,  394,  393,  392,  391,  390,  389,
      388,  387,  386,  385,  384,  383,  328,  382,  381,  379,

      378,  377,  372,  371,  370,  369,  368,  367,  366,  365,
      360,  359,  358,  357,  356,  355,  298,  354,  353,  352,
      187,  351,  187,  350,  349,  348,  347,  346,  345,  344,
      343,  342,  341,  340,  339,  338,  337,  336,  335,  334,
      333,  332,  328,  331,  330,  328,  328,  327,  326,  325,
      324,  321,  320,  317,  316,  315,  314,  311,  310,  307,
      306,  305,  304,  298,  303,  302,  301,  300,  298,  299,
      298,  297,  296,  187,  295,  294,  293,  292,  291,  290,
      289,  288,  287,  286,  285,  284,  283,  282,  281,  280,
      279,  277,  276,  275,  274,  273,  270,  269,  250,  249,

      248,  247,  246,  245,  244,  243,  242,  241,  240,  187,
      239,  238,  237,  236,  235,  187,  231,  230,  229,  228,
      227,  226,  225,  224,  223,  222,  221,  220,  219,  218,
      217,  216,  215,  214,  207,  201,  200,  199,  198,  197,
      196,  195,  194,  193,  192,  191,  190,  189,  188,  187,
      187,  186,  185,  184,  183,  182,  181,  177,  176,  175,
      174,  173,  172,  171,  170,  169,  168,  165,  164,  163,
      162,  161,  160,  159,  157,  156,  155,  154,  153,  152,
      151,  150,  145,  144,  143,  142,  141,  140,  139,  138,
      137,  136,  135,  134,  133,  128,  127,  126,  125,  124,

      123,  111,  110,  109,  108,  105,  104,   99,   98,   97,
       92,   91,   90,   83,   82,   81,   80,   79,   73,   72,
       65,   32,  560,    3,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560
    } ;

static yyconst flex_int16_t yy_chk[1185] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,

        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,   10,   10,   10,   10,
       10,   10,   11,   12,   14,   17,   16,   18,   14,   21,
       22,   41,  516,   21,   11,   12,   16,   42,   57,   18,
       22,   46,   17,   50,  516,   46,   21,   42,   41,   47,
       57,   50,   11,   12,   33,   56,   56,   33,   47,   55,
       33,   33,   33,   33,   33,   33,  557,  556,   57,   55,
       69,   33,   69,   33,   55,  207,   33,   33,   33,   33,
       35,   35,   35,   35,   35,   35,   33,   33,   33,   33,
       36,   33,   33,   33,   36,   33,   58,   70,   33,   33,

       33,   33,  207,  150,   70,  150,   36,  543,   58,   59,
       59,   59,   59,   59,   59,   60,   60,   60,   60,   60,
       60,  313,  539,  313,   36,   37,   58,  106,   62,   37,
      535,   37,   37,   37,   37,   37,   37,   61,  150,   61,
       62,   37,   61,   61,   61,   61,   61,   61,   87,   87,
       87,   87,   87,   87,  534,  151,  106,  151,   62,   37,
       85,  117,  271,  122,   85,  531,   85,   85,   85,   85,
       85,   85,   88,  117,   88,  122,   85,   88,   88,   88,
       88,   88,   88,  119,  119,  119,  119,  119,  119,  271,
      151,  117,  529,  122,   85,   89,  155,  526,  155,   89,

      525,   89,   89,   89,   89,   89,   89,  153,  154,  153,
      154,   89,  118,  118,  118,  118,  118,  118,  156,  256,
      156,  264,  118,  120,  120,  120,  120,  120,  120,   89,
      121,  121,  121,  121,  121,  121,  256,  314,  264,  324,
      118,  146,  155,  154,  314,  146,  324,  146,  146,  146,
      146,  146,  146,  147,  253,  180,  153,  146,  253,  147,
      147,  147,  147,  147,  147,  156,  157,  180,  157,  147,
      261,  323,  524,  323,  261,  146,  148,  148,  148,  148,
      148,  148,  149,  520,  328,  180,  328,  147,  149,  149,
      149,  149,  149,  149,  178,  364,  178,  364,  519,  178,

      178,  178,  178,  178,  178,  202,  376,  202,  376,  157,
      202,  202,  202,  202,  202,  202,  203,  203,  518,  203,
      203,  203,  203,  203,  514,  203,  204,  204,  513,  204,
      204,  204,  204,  204,  512,  204,  232,  232,  232,  232,
      232,  232,  233,  233,  233,  233,  233,  233,  234,  251,
      251,  251,  251,  251,  251,  252,  356,  357,  356,  357,
      234,  252,  252,  252,  252,  252,  252,  358,  359,  358,
      359,  360,  361,  360,  361,  362,  510,  362,  234,  363,
      365,  363,  365,  366,  367,  366,  367,  369,  368,  369,
      368,  509,  371,  370,  371,  370,  356,  372,  373,  372,

      373,  502,  379,  358,  379,  374,  357,  374,  375,  501,
      375,  362,  500,  363,  359,  499,  365,  377,  517,  377,
      360,  378,  406,  378,  406,  361,  498,  366,  368,  370,
      517,  417,  367,  417,  496,  464,  369,  464,  371,  495,
      532,  374,  375,  465,  494,  465,  372,  486,  486,  486,
      379,  373,  532,  377,  399,  399,  399,  399,  399,  399,
      487,  487,  487,  493,  492,  378,  400,  400,  400,  400,
      400,  400,  411,  411,  411,  411,  411,  411,  436,  436,
      436,  436,  436,  436,  437,  437,  437,  437,  437,  437,
      488,  488,  488,  503,  503,  503,  503,  503,  503,  504,

      504,  504,  504,  504,  504,  505,  505,  505,  505,  506,
      506,  506,  506,  506,  506,  507,  507,  507,  507,  507,
      507,  508,  508,  508,  508,  521,  521,  521,  521,  521,
      522,  522,  522,  522,  522,  523,  523,  523,  523,  523,
      527,  527,  527,  527,  527,  527,  528,  528,  528,  528,
      528,  528,  533,  536,  536,  536,  536,  536,  537,  537,
      537,  537,  537,  491,  533,  538,  538,  538,  538,  538,
      541,  541,  541,  541,  541,  541,  542,  542,  542,  542,
      542,  542,  544,  545,  544,  545,  547,  547,  547,  547,
      547,  547,  548,  548,  548,  548,  548,  548,  549,  549,

      549,  549,  549,  549,  550,  550,  550,  550,  550,  550,
      551,  551,  551,  551,  551,  551,  552,  552,  552,  552,
      552,  552,  553,  553,  553,  553,  553,  553,  554,  554,
      554,  554,  554,  554,  555,  555,  555,  555,  555,  555,
      561,  561,  562,  562,  563,  490,  489,  484,  563,  564,
      564,  565,  565,  566,  566,  566,  567,  567,  568,  568,
      568,  569,  569,  570,  570,  570,  570,  570,  570,  571,
      571,  571,  572,  483,  481,  480,  572,  573,  573,  573,
      574,  574,  574,  575,  575,  575,  576,  576,  576,  577,
      577,  577,  479,  478,  477,  476,  475,  474,  473,  472,

      471,  470,  469,  468,  467,  466,  463,  462,  461,  458,
      457,  455,  454,  453,  451,  450,  449,  448,  447,  446,
      445,  444,  443,  442,  441,  440,  439,  438,  435,  434,
      433,  432,  430,  429,  428,  427,  426,  425,  424,  423,
      421,  420,  419,  418,  416,  415,  414,  413,  412,  410,
      409,  408,  407,  405,  404,  403,  402,  401,  398,  397,
      396,  395,  394,  393,  392,  390,  389,  388,  387,  386,
      385,  384,  383,  382,  381,  355,  354,  353,  352,  351,
      350,  349,  347,  346,  345,  344,  343,  342,  341,  340,
      339,  338,  337,  336,  335,  334,  333,  332,  331,  327,

      326,  325,  322,  321,  320,  319,  318,  317,  316,  315,
      312,  311,  310,  309,  308,  306,  305,  304,  303,  302,
      301,  300,  299,  297,  296,  294,  293,  291,  290,  288,
      287,  286,  285,  284,  283,  282,  281,  280,  279,  277,
      276,  275,  274,  273,  272,  270,  269,  268,  267,  266,
      265,  263,  262,  260,  259,  258,  257,  255,  254,  250,
      248,  247,  246,  245,  244,  243,  242,  241,  240,  239,
      238,  237,  236,  235,  231,  229,  228,  227,  226,  225,
      224,  223,  222,  221,  220,  219,  218,  217,  216,  215,
      214,  212,  211,  210,  209,  208,  206,  205,  200,  198,

      197,  196,  195,  194,  193,  192,  191,  190,  189,  188,
      186,  185,  184,  183,  182,  181,  177,  176,  175,  174,
      173,  172,  171,  170,  169,  168,  167,  165,  164,  163,
      162,  161,  160,  159,  152,  145,  144,  143,  142,  141,
      140,  139,  138,  137,  136,  135,  134,  133,  131,  130,
      129,  128,  127,  126,  125,  124,  123,  116,  115,  114,
      113,  112,  111,  110,  109,  108,  107,  105,  104,  103,
      102,  101,  100,   99,   97,   96,   95,   94,   93,   92,
       91,   90,   83,   82,   81,   80,   79,   78,   77,   76,
       75,   74,   73,   72,   71,   68,   67,   66,   65,   64,

       63,   54,   53,   52,   51,   49,   48,   45,   44,   43,
       40,   39,   38,   29,   28,   27,   26,   23,   20,   19,
       15,    7,    3,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560,  560,  560,  560,  560,  560,  560,
      560,  560,  560,  560
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "myflex.l"
#line 2 "myflex.l"
    #include<stdio.h>
    #include "mybison.tab.h"
    char *strclone(char *str);
    int line_num = 1;
    
#line 912 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 54 "myflex.l"

#line 1128 "lex.yy.c"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 561 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1124 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 55 "myflex.l"
{
      yylval.string=strdup(yytext);
                 return CREATED_BODY;
};
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 59 "myflex.l"
{
      yylval.string=strdup(yytext);
                 return FULL;
};
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 63 "myflex.l"
{
      yylval.string=strdup(yytext);
                 return EXTENDED;
};
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 68 "myflex.l"
{
      yylval.string=strdup(yytext);
                 return ENTITIES;
};
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 73 "myflex.l"
{
      yylval.string=strdup(yytext);
                 return HASHTAGS;
};
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 78 "myflex.l"
{
      yylval.string=strdup(yytext);
                 return INDICES;
};
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 83 "myflex.l"
{
      yylval.string=strdup(yytext);
                 return TWEET;
};
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 88 "myflex.l"
{
      yylval.string=strdup(yytext);
                 return RETWEETED_STATUS;
};
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 92 "myflex.l"
{
      yylval.string=strdup(yytext);
                 return ID_BODY;
};
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 96 "myflex.l"
{
     yylval.string=strclone(yytext);
                    return TEXT;
};
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 100 "myflex.l"
{
     yylval.string=strclone(yytext);
                    return ID;
};
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 104 "myflex.l"
{
     yylval.string=strclone(yytext);
                    return USER;
};
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 108 "myflex.l"
{
     yylval.string=strclone(yytext);
                    return NAME;
};
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 112 "myflex.l"
{
     yylval.string=strclone(yytext);
                    return SCREEN_NAME;
};
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 116 "myflex.l"
{
     yylval.string=strclone(yytext);
                    return LOCATION;
};
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 120 "myflex.l"
{
     yylval.string=strclone(yytext);
                    return CREATED_AT;
};
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 124 "myflex.l"
{
     yylval.string=strclone(yytext);
                    return DESCRIPTION;
};
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 128 "myflex.l"
{
     yylval.string=strclone(yytext);
                    return URL;
};
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 132 "myflex.l"
{
     yylval.string=strclone(yytext);
                    return ID_STR;
};
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 136 "myflex.l"
{
      yylval.string=strdup(yytext);
                 return RT_BODY;
};
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 140 "myflex.l"
{
      yylval.string=strdup(yytext);
                 return TRUNCATED;
};
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 144 "myflex.l"
{
      yylval.string=strdup(yytext);
                 return DISPLAY;
};
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 148 "myflex.l"
;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 149 "myflex.l"
{return STRING;};
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 150 "myflex.l"
{
    yylval.string=strclone(yytext);
    return STRING;
};
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 154 "myflex.l"
{ 
    yylval.string=strclone(yytext);
    return NUMBER;
};
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 158 "myflex.l"
{return DBL_QUOTE;};
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 159 "myflex.l"
{
     yylval.string=strclone(yytext);
     return TRUE1;
};
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 163 "myflex.l"
{return SPACE;};
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 164 "myflex.l"
{
     yylval.string=strclone(yytext);
    return FALSE1;
};
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 168 "myflex.l"
{
    return null;
};
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 171 "myflex.l"
{
    return CURLY_BRACKET_L;
};
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 175 "myflex.l"
{
    return CURLY_BRACKET_R;
};
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 179 "myflex.l"
{
    return L_SQUARE_BRACKET;
};
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 183 "myflex.l"
{
    return R_SQUARE_BRACKET;
};
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 187 "myflex.l"
{
    return COMMA;
};
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 190 "myflex.l"
{
    return COLON;
};
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 194 "myflex.l"
{return DAY;};
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 195 "myflex.l"
{return MONTH;};
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 196 "myflex.l"
{return YEAR;};
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 197 "myflex.l"
{return DATE;};
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 201 "myflex.l"
++line_num; 
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 202 "myflex.l"
{
    printf("Unexpected: %c\nExiting...\n",*yytext);
    exit(0);
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 206 "myflex.l"
0;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 207 "myflex.l"
ECHO;
	YY_BREAK
#line 1506 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 561 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 561 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 560);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 206 "myflex.l"


char *strclone(char *str)
{
    int len = strlen(str);
    char *clone = (char *)malloc(sizeof(char)*(len+1));
    strcpy(clone,str);
    return clone;
}
